apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: MPI
metadata:
  name: test-mpi
spec:
  job:
    apiVersion: batch/v1
    kind: Job
    spec:
      completions: 6
      parallelism: 6
      template:
        spec:
          containers:
          - image: continuse/mpich:v3
            imagePullPolicy: IfNotPresent
            name: mpi
            command: ["mpirun", "-n", "6", "hostname"] #, "cat", "/mpi/hostfile"]
            resources:
              requests:
                cpu: "200m"
  podGroup:
    spec:
      minMember: 6