apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: mpis.scheduling.incubator.k8s.io
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: MPI
    plural: mpis
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            job:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: object
            podGroup:
              properties:
                apiVersion:
                  description: 'APIVersion defines the versioned schema of this representation
                    of an object. Servers should convert recognized schemas to the
                    latest internal value, and may reject unrecognized values. More
                    info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                  type: string
                kind:
                  description: 'Kind is a string value representing the REST resource
                    this object represents. Servers may infer this from the endpoint
                    the client submits requests to. Cannot be updated. In CamelCase.
                    More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                  type: string
                metadata:
                  description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
                  type: object
                spec:
                  description: 'Specification of the desired behavior of the pod group.
                    More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status'
                  properties:
                    minMember:
                      description: MinMember defines the minimal number of members/tasks
                        to run the pod group; if there's not enough resources to start
                        all tasks, the scheduler will not start anyone.
                      format: int32
                      type: integer
                    queue:
                      description: Queue defines the queue to allocate resource for
                        PodGroup; if queue does not exist, the PodGroup will not be
                        scheduled.
                      type: string
                  type: object
                status:
                  description: Status represents the current information about a pod
                    group. This data may not be up to date.
                  properties:
                    failed:
                      description: The number of pods which reached phase Failed.
                      format: int32
                      type: integer
                    running:
                      description: The number of actively running pods.
                      format: int32
                      type: integer
                    succeeded:
                      description: The number of pods which reached phase Succeeded.
                      format: int32
                      type: integer
                  type: object
              type: object
          required:
          - job
          - podGroup
          type: object
        status:
          properties:
            descriptors:
              description: additional job descriptors
              type: object
            job:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file the job status'
              type: object
            podGroup:
              description: the podGroup status
              properties:
                failed:
                  description: The number of pods which reached phase Failed.
                  format: int32
                  type: integer
                running:
                  description: The number of actively running pods.
                  format: int32
                  type: integer
                succeeded:
                  description: The number of pods which reached phase Succeeded.
                  format: int32
                  type: integer
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
